FROM node:lts-alpine3.14 as builder
WORKDIR /usr/src/app
COPY . .
RUN npm install && npm run prod_build

FROM nginxinc/nginx-unprivileged:1-alpine-amd64
WORKDIR /app
EXPOSE 8080
COPY --from=builder /usr/src/app/build .

#docker run -ti --rm -p 80:80 -v $("pwd")/nginx.conf:/etc/nginx/nginx.conf:ro rap-fend_prod
